primary_region = "fra"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[env]
  SERVICE_NAME = "backend"
  SITE_URL = "https://nopo-prod.fly.dev"
  PORT = 3_000

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024

[[statics]]
  guest_path = "/app/apps/backend/build"
  url_prefix = "/api/static"

console_command = "/bin/bash"

[deploy]
  release_command = "pnpm run --filter=@more/backend migrate"

