services:
  base:
    image: "${DOCKER_TAG:?}"
    pull_policy: never
    restart: always
    volumes:
      - nopo_uv_cache:/home/nopoapp/.uv
      - nopo_pnpm_store:/home/nopoapp/.local/share/pnpm/store
      - nopo_venv:/home/nopoapp/.venv
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI
      - SITE_URL

volumes:
  nopo_uv_cache:
  nopo_pnpm_store:
  nopo_venv:
